name: Hunt NIO in Smali

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

jobs:
  hunt-nio:
    runs-on: ubuntu-latest

    steps:
      - run: curl -sSL -o npatch.jar https://github.com/WinterWolfVN/KettuManager/raw/refs/heads/main/app/libs/jar-v0.8.0-538-release.jar

      - run: zip -q -d npatch.jar "*.dex" || true

      - run: |
          D8_PATH=$(find $ANDROID_HOME/build-tools -name d8 | sort -r | head -n 1)
          $D8_PATH --min-api 24 --output . npatch.jar

      - run: curl -sSL -o baksmali.jar https://bitbucket.org/JesusFreke/smali/downloads/baksmali-2.5.2.jar

      - run: java -jar baksmali.jar d classes.dex -o smali_out

      - run: grep -rn "Ljava/nio/file/Files;->" smali_out/ || true
